<?php
/**
 * Created by PhpStorm.
 * User: bryce
 * Date: 1/15/16
 * Time: 3:34 PM
 */

namespace ElegantSlider\Admin;



use ElegantSlider\Model\Slider;

class Create extends Edit {

    public function processRequest($action = null) {

        $this->slider = Slider::create([]);

        $this->slider->createPlaceholderImage();

        parent::processRequest($action); // TODO: Change the autogenerated stub
    }
}